### ISSUE TITLE
Symfony 3 support?

### ISSUE THREAD

**Issue by TiGR** [KnpLabs/ConsoleServiceProvider#17]
AFAIK, there are no incompatible API changes related to ConsoleServiceProvider in symfony/console v. 3. So, maybe just change `"~2.1"` in `composer.json` to `">2.1"`?

**Comment by pCyril** [comment]
+1

**Comment by Nek-** [comment]
Hello,

This repo may not be maintained at all anymore. But you still can make a pull-request and hope it will be merged. (I guess the composer fix is the only thing to do)
