### ISSUE TITLE
Abbandon project

### ISSUE THREAD

**Issue by ivoba** [KnpLabs/ConsoleServiceProvider#19]
Seems this project is unmaintained, you might want to change the description and abbandon it on packagist.org.

I started a new forkoff here https://github.com/ivoba/console-service-provider

**Comment by weaverryan** [comment]
ping @ubermuda you're listed as the maintainer, so it's up to you, but it makes sense to me.

**Comment by ubermuda** [comment]
Hi @ivoba, @weaverryan,

I just marked the package as abandoned on packagist, with a heads up to `ivoba/console-service-provider`.

I do not have the rights anymore to modify the description of the github repository though, someone else will have to do it.

**Comment by weaverryan** [comment]
Thanks @ubermuda - I updated the description and adding something to the readme :)
