### ISSUE TITLE
Please add the MIT license file to the repo

### ISSUE THREAD

**Issue by uda** [KnpLabs/ConsoleServiceProvider#21]
I need it for legal stuff...
Those lawyers...

**Comment by weaverryan** [comment]
ping @ubermuda I think you would need to do that...

**Comment by weaverryan** [comment]
I believe we would need an "ok" from all the people that have committed to this repository.

But, other than README changes and `composer.json` changes, only these two people have committed real code changes.

* @rybakit are you ok if we add an MIT license to this repository? You once committed a small code change. Give me a 👍 if you are ok with that licensing your small change as MIT.

* @ubermuda same question - 👍 for licensing your commits as MIT?

**Comment by rybakit** [comment]
@weaverryan :+1:

**Comment by ubermuda** [comment]
@weaverryan sure thing 👍

**Comment by weaverryan** [comment]
@CrimsonLabs We can now add an MIT license to the repository

**Comment by CrimsonLabs** [comment]
done - created pull request

**Comment by CrimsonLabs** [comment]
hey @ubermuda - This has been done.
