### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by CrimsonLabs** [KnpLabs/ConsoleServiceProvider#22]
Good Day, I am interested in maintaining this product. Please assist?

**Comment by weaverryan** [comment]
@CrimsonLabs If you're interested, the best thing to do is to review the existing pull requests to see if we should merge or close them. And if you have any changes you'd like, you can open new PR's. I'll be here to help - and if everything is working well, I can give you commit access :)

**Comment by CrimsonLabs** [comment]
Sounds good to me :) I'll get on it ASAP

**Comment by weaverryan** [comment]
Great start :). If you want, you can make a PR to update the README to list you as the maintainer, and I can give you write access. I'm happy to continue to help review issues and PR's for a bit, if you'd like.

**Comment by CrimsonLabs** [comment]
done, thanks @weaverryan
