### ISSUE TITLE
ServiceProviderInterface

### ISSUE THREAD

**Issue by leonlombard** [KnpLabs/ConsoleServiceProvider#25]
When using silex 2.0 and registering the ConsoleServiceProvider I get the following error: "Interface 'Silex\ServiceProviderInterface' not found in /vagrant/vendor/knplabs/console-service-provider/Knp/Provider/ConsoleServiceProvider.php on line 13"

Upon further investigation it seems the providers are using the Pimple/ServiceProviderInterface and the Silex/ServiceProviderInterface class does not exist.

Is there something I am missing or is this an update that needs to be done due to updates in the silex framework?

**Comment by CrimsonLabs** [comment]
Hi @leonlombard 

A Silex 2 version of this application is on it's way in the next few days, will keep you udpated

**Comment by leonlombard** [comment]
Great news! Thanks.

**Comment by CrimsonLabs** [comment]
This will be resolved by pull request #8 @weaverryan can we discuss?

**Comment by CrimsonLabs** [comment]
Ok @leonlombard please update to version 2.0 for Silex 2 compatibility

**Comment by leonlombard** [comment]
Great! Thanks guys.
