### ISSUE TITLE
calling add() function on a non object

### ISSUE THREAD

**Issue by ravitej91** [KnpLabs/ConsoleServiceProvider#7]
the following is my console code, but when I try to run this code I'm getting the error that $application is non-object. I tried in many other ways but same issue, Tried to dump $application giving me a knp command object. Please tell me whats wrong with my code.

#!/usr/bin/env php
<?php
define('BASE_DIR', realpath(__DIR__ . '/..'));
require_once __DIR__.'/config.php';
require_once __DIR__.'/Command/x.php';

$app = require_once __DIR__.'/bootstrap.php';

use y\src\Command\x;

$application = $app['console'];

$application->add(new x());
$application->run();

**Comment by CrimsonLabs** [comment]
Hi @ravitej91 - I have just taken over maintenance of this repository - did you come right with this?
